# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-19 22:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddressRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('addrLine1', models.CharField(default='nothing', max_length=200, null=True)),
                ('addrLine2', models.CharField(default='nothing', max_length=200, null=True)),
                ('pincode', models.CharField(default='nothing', max_length=10, null=True)),
                ('city', models.CharField(default='nothing', max_length=100, null=True)),
                ('state', models.CharField(default='nothing', max_length=100, null=True)),
                ('country', models.CharField(default='nothing', max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyInfoRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('companyName', models.CharField(default='nothing', max_length=254, null=True)),
                ('companyAddress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='companyAddress', to='userAccountApp.AddressRecord')),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyContactRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('relationship1', models.CharField(default='nothing', max_length=254, null=True)),
                ('relationship2', models.CharField(default='nothing', max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdentityTypeRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('docType', models.CharField(default='nothing', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='IdVerificationRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('idDocsURLlist', models.TextField(default='[]')),
                ('idType', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identityType', to='userAccountApp.IdentityTypeRecord')),
            ],
        ),
        migrations.CreateModel(
            name='PersonalInfoRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='nothing', max_length=254, null=True)),
                ('last_name', models.CharField(default='nothing', max_length=254, null=True)),
                ('middle_name', models.CharField(default='nothing', max_length=254, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(default='99999999', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserAccountRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('profilePhotolist', models.TextField(default='[]')),
                ('mailingAddress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mailingAddress', to='userAccountApp.AddressRecord')),
                ('permanentAddress', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='permanentAddress', to='userAccountApp.AddressRecord')),
                ('userInfo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userInfo', to='userAccountApp.PersonalInfoRecord')),
            ],
        ),
        migrations.AddField(
            model_name='emergencycontactrecord',
            name='contactInfo1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergencyInfo1', to='userAccountApp.PersonalInfoRecord'),
        ),
        migrations.AddField(
            model_name='emergencycontactrecord',
            name='contactInfo2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergencyInfo2', to='userAccountApp.PersonalInfoRecord'),
        ),
    ]
