# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-19 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccountApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalinforecord',
            name='gender',
            field=models.CharField(default='nothing', max_length=254, null=True),
        ),
    ]
