# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-21 19:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userAccountApp', '0003_auto_20181220_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccountrecord',
            name='occupation',
            field=models.CharField(default='occupation', max_length=254, null=True),
        ),
    ]
